### ISSUE TITLE
Hosted documentation

### ISSUE THREAD

**Issue by cmtt** [ratel-rust/ratel-core#53]
As follow-up task of #25, `ratel-core` should use [`rustdoc`](https://doc.rust-lang.org/book/documentation.html) for documentation. 

Generated content could be hosted using [GitHub Pages](https://pages.github.com/) or in scope of #26.

**Comment by maciejhirsz** [comment]
Or just use https://docs.rs/ratel/0.7.0/ratel/ :)

**Comment by cmtt** [comment]
Ok, closing this issue.
