### ISSUE TITLE
Parse `NaN` and `Infinity / -Infinity`

### ISSUE THREAD

**Issue by LuoZijun** [ratel-rust/ratel-core#84]
Keywords:

* `NaN / +NaN / -NaN`      --> `std::f64::NAN`
* `Infinity / +Infinity`  --> `std::f64::INFINITY`
* `-Infinity` --> `std::f64::NEG_INFINITY`

These keywords need to be parsed into `Literal`, not an `Identifier` .

**Comment by cmtt** [comment]
[NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) and [Infinity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity) are properties of the global object (`window` in a browser environment), e.g. acessible as `global.NaN` or `global.Inifnity`.

Thus, they are not parsed as special literals, see also the exhaustive list of literals in the [ECMAScript 2015 specification](https://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-lexical-grammar-literals).
