### ISSUE TITLE
Bad link in README.md

### ISSUE THREAD

**Issue by Yoric** [ratel-rust/ratel-core#92]
The following link
https://camo.githubusercontent.com/1ea558cf5608a653c9e3b85bc9953181ee80d2d2/687474703a2f2f7465726869782e636f6d2f726174656c2d706572662d312e706e67

returns "Cannot proxy the given URL"

**Comment by cmtt** [comment]
Hello @Yoric, thank you for the response. The image has been removed from GitHub, but find attached is an updated graphic. I will update the README.
![ratel-benches](https://user-images.githubusercontent.com/787228/46630876-e7fb7b00-cb45-11e8-9f0f-c9b4d89aca9b.png)

**Comment by Yoric** [comment]
Cool result :)

You may wish to compare to the Shift parser, too.

**Comment by maciejhirsz** [comment]
We really need to start benching actual transformations, without transferring the AST over to JS context the chart should be mostly flat ;).

**Comment by Yoric** [comment]
These perfs look nice. I should really take a swab at porting https://github.com/binast/binjs-ref to ratel core. @cmtt, @maciejhirsz, how stable is the AST itself?

**Comment by Yoric** [comment]
Mmmh... Or perhaps I should port Ratel Core to Binjs-ref :)

**Comment by cmtt** [comment]
Hi @Yoric,

we intend to follow the ESTree spec as close as possible, but ratel is currently using a slightly different AST internally. Support for optionally returning the BinAST format would help in the long run in order to speed other JavaScript-related tools up which already use BinAST.

**Comment by maciejhirsz** [comment]
I think the AST is reasonably stable for at least having a go at it. I'm still considering adding some generic magic to allow for different flavors of JS, and it's hard for me to tell if those would affect BinAST withouth reading further (is there, f.e.: a uniform agreement on how to handle TS types, or are those things outside of the scope of the format)?

**Comment by Yoric** [comment]
> I think the AST is reasonably stable for at least having a go at it.

I think the lowest risk for everyone is to create a crate to convert Ratel <-> BinAST. I'll take a stab at this.

> I'm still considering adding some generic magic to allow for different flavors of JS, and it's hard for me to tell if those would affect BinAST withouth reading further (is there, f.e.: a uniform agreement on how to handle TS types, or are those things outside of the scope of the format)?

TS types are outside the scope of the format.

> Support for optionally returning the BinAST format would help in the long run in order to speed other JavaScript-related tools up which already use BinAST.

For the moment, BinAST is still unstable, so only `binjs-ref` uses this AST.

**Comment by maciejhirsz** [comment]
> I think the lowest risk for everyone is to create a crate to convert Ratel <-> BinAST. I'll take a stab at this.

That would be really awesome!

**Comment by Yoric** [comment]
Tracking the effort at https://github.com/binast/binjs-ref/issues/229 .

I have a few lines of code. It's going to be a tad painful to write :/
